version: '3'

vars:
  ENGINE_DIR: ./engine
  # Android NDK configuration
  # Override with ANDROID_NDK_HOME environment variable if different
  ANDROID_NDK_HOME:
    sh: echo "${ANDROID_NDK_HOME:-$HOME/Library/Android/sdk/ndk/26.1.10909125}"
  ANDROID_NDK_TOOLCHAIN: '{{.ANDROID_NDK_HOME}}/toolchains/llvm/prebuilt/darwin-x86_64/bin'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the Rust engine
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo build

  build:release:
    desc: Build the Rust engine in release mode
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo build --release

  test:
    desc: Run Rust tests
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo test

  test:watch:
    desc: Run Rust tests in watch mode
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo watch -x test

  check:
    desc: Check Rust code without building
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo check

  clippy:
    desc: Run Clippy linter
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo clippy -- -D warnings

  fmt:
    desc: Format Rust code
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check Rust code formatting
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo fmt -- --check

  clean:
    desc: Clean build artifacts
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo clean

  doc:
    desc: Generate and open Rust documentation
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo doc --open

  ci:
    desc: Run all CI checks (fmt, clippy, test, build)
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test
      - task: build

  dev:
    desc: Development mode - watch and rebuild on changes
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - cargo watch -x check -x test -x build

  generate:
    desc: Generate Tailwind class map from theme.toml
    cmds:
      - go run tools/generate/main.go

  generate:watch:
    desc: Watch theme.toml and regenerate on changes
    cmds:
      - watchexec -w theme.toml -- task generate

  # iOS tasks
  ios:build:
    desc: Build Rust engine for iOS device (aarch64-apple-ios)
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - rustup target add aarch64-apple-ios 2>/dev/null || true
      - cargo build --release --lib --target aarch64-apple-ios

  ios:build:sim:
    desc: Build Rust engine for iOS simulator (aarch64-apple-ios-sim)
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - rustup target add aarch64-apple-ios-sim 2>/dev/null || true
      - cargo build --release --lib --target aarch64-apple-ios-sim

  ios:build:all:
    desc: Build Rust engine for both iOS device and simulator
    cmds:
      - task: ios:build
      - task: ios:build:sim

  ios:framework:
    desc: Build iOS framework with gomobile (rebuilds Go code for iOS)
    dir: examples/ios_demo
    cmds:
      - echo "Building iOS framework with gomobile..."
      - PATH="$HOME/go/bin:$PATH" gomobile bind -target iossimulator -o CenteredDemo.xcframework .
      - echo "Framework built at examples/ios_demo/CenteredDemo.xcframework"

  ios:clean:
    desc: Clean Xcode derived data for iOS demo
    vars:
      DERIVED_DATA: '{{.HOME}}/Library/Developer/Xcode/DerivedData'
    cmds:
      - echo "Cleaning Xcode derived data..."
      - rm -rf {{.DERIVED_DATA}}/CenteredDemo* {{.DERIVED_DATA}}/CenteredDemoApp*
      - echo "Done"

  ios:rebuild:
    desc: Full rebuild of iOS demo (framework + clean Xcode cache)
    cmds:
      - task: ios:framework
      - task: ios:clean
      - echo "iOS demo rebuilt. Open Xcode and run the project."

  ios:run:
    desc: Build, deploy and run iOS demo on simulator
    vars:
      XCODE_PROJECT: examples/ios_demo/XcodeProject/CenteredDemoApp.xcodeproj
      BUNDLE_ID: com.centered.demo
      DERIVED_DATA: '{{.HOME}}/Library/Developer/Xcode/DerivedData'
    cmds:
      - task: ios:build:sim
      # Find the DerivedData folder for CenteredDemoApp
      - |
        APP_DIR=$(find {{.DERIVED_DATA}} -name "CenteredDemoApp-*" -type d 2>/dev/null | head -1)
        if [ -z "$APP_DIR" ]; then
          echo "Building Xcode project first..."
          xcodebuild -project {{.XCODE_PROJECT}} -scheme CenteredDemoApp -sdk iphonesimulator -configuration Debug build
          APP_DIR=$(find {{.DERIVED_DATA}} -name "CenteredDemoApp-*" -type d 2>/dev/null | head -1)
        fi
        APP_BUNDLE="$APP_DIR/Build/Products/Debug-iphonesimulator/CenteredDemoApp.app"
        echo "Copying dylib to app bundle..."
        mkdir -p "$APP_BUNDLE/Frameworks"
        cp {{.ENGINE_DIR}}/target/aarch64-apple-ios-sim/release/libcentered_engine.dylib "$APP_BUNDLE/Frameworks/"
        echo "Installing on simulator..."
        open -a Simulator
        sleep 2
        xcrun simctl install booted "$APP_BUNDLE"
        echo "Launching app..."
        xcrun simctl launch --console booted {{.BUNDLE_ID}}

  # Android tasks
  android:build:
    desc: Build Rust engine for Android device (aarch64-linux-android)
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - rustup target add aarch64-linux-android 2>/dev/null || true
      - PATH="{{.ANDROID_NDK_TOOLCHAIN}}:$PATH" cargo build --release --lib --target aarch64-linux-android

  android:build:sim:
    desc: Build Rust engine for Android emulator (x86_64-linux-android)
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - rustup target add x86_64-linux-android 2>/dev/null || true
      - PATH="{{.ANDROID_NDK_TOOLCHAIN}}:$PATH" cargo build --release --lib --target x86_64-linux-android

  android:build:all:
    desc: Build Rust engine for all Android targets (arm64, armv7, x86_64)
    dir: '{{.ENGINE_DIR}}'
    cmds:
      - rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android 2>/dev/null || true
      - PATH="{{.ANDROID_NDK_TOOLCHAIN}}:$PATH" cargo build --release --lib --target aarch64-linux-android
      - PATH="{{.ANDROID_NDK_TOOLCHAIN}}:$PATH" cargo build --release --lib --target armv7-linux-androideabi
      - PATH="{{.ANDROID_NDK_TOOLCHAIN}}:$PATH" cargo build --release --lib --target x86_64-linux-android

  android:framework:
    desc: Build Android AAR with gomobile (rebuilds Go code for Android)
    dir: examples/android_demo
    cmds:
      - echo "Building Android AAR with gomobile..."
      - mkdir -p app/libs
      - PATH="$HOME/go/bin:$PATH" gomobile bind -target android/arm64 -androidapi 24 -o app/libs/centered_go.aar .
      - echo "AAR built at examples/android_demo/app/libs/centered_go.aar"

  android:clean:
    desc: Clean Android build artifacts
    cmds:
      - rm -rf {{.ENGINE_DIR}}/target/aarch64-linux-android
      - rm -rf {{.ENGINE_DIR}}/target/armv7-linux-androideabi
      - rm -rf {{.ENGINE_DIR}}/target/x86_64-linux-android
      - rm -rf examples/android_demo/app/build
      - rm -rf examples/android_demo/app/libs/*.aar
      - rm -rf examples/android_demo/app/src/main/jniLibs
      - echo "Android build artifacts cleaned"

  android:rebuild:
    desc: Full rebuild of Android demo (framework + clean)
    cmds:
      - task: android:framework
      - task: android:clean
      - echo "Android demo rebuilt. Run 'task android:run' to build and install."

  android:run:
    desc: Build, deploy and run Android demo on device/emulator
    vars:
      BUNDLE_ID: com.centered.demo
    cmds:
      - task: android:build
      - |
        echo "Copying .so to jniLibs..."
        mkdir -p examples/android_demo/app/src/main/jniLibs/arm64-v8a
        cp {{.ENGINE_DIR}}/target/aarch64-linux-android/release/libcentered_engine.so examples/android_demo/app/src/main/jniLibs/arm64-v8a/
      - |
        echo "Building and installing APK..."
        cd examples/android_demo && ./gradlew installDebug
      - |
        echo "Launching app..."
        adb shell am start -n {{.BUNDLE_ID}}/.CenteredActivity

  android:logcat:
    desc: Show Android logcat filtered for Centered
    cmds:
      - adb logcat -s Centered:V centered_engine:V AndroidRuntime:E
