// Objective-C API for talking to github.com/agiangrant/centered/examples/ios_demo Go package.
//   gobind -lang=objc github.com/agiangrant/centered/examples/ios_demo
//
// File is generated by gobind. Do not edit.

#ifndef __Ios_demo_H__
#define __Ios_demo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Ios_demoDemoWidgetRefs;

/**
 * DemoWidgetRefs holds references to widgets we want to interact with
 */
@interface Ios_demoDemoWidgetRefs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field DemoWidgetRefs.CounterText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.StatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.Button1 with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.Button2 with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.Button3 with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.AudioWidget with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.AudioButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.AudioStatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.MicWidget with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.MicButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.MicStatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.MicLevelText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.VideoWidget with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.VideoButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.VideoStatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.CameraWidget with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.CameraButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.CameraStatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.ClipboardCopyButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.ClipboardPasteButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.ClipboardStatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.HapticLightButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.HapticMediumButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.HapticHeavyButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.HapticSelectionBtn with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.HapticSuccessButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.HapticStatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.KeyboardInput with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.KeyboardShowButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.KeyboardHideButton with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.KeyboardStatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

@end

/**
 * Dummy export required by gomobile
 */
FOUNDATION_EXPORT void Ios_demoDummy(void);

/**
 * IOSMain is the entry point for the iOS app.
This should be called from main.m (which is the actual iOS entry point).
It handles the full app lifecycle via ffi.Run().
 */
FOUNDATION_EXPORT void Ios_demoIOSMain(void);

/**
 * Main is exported for testing on desktop
 */
FOUNDATION_EXPORT void Ios_demoMain(void);

/**
 * StartDemo initializes and starts the demo app.
On iOS, this is called via IOSMain().
On desktop, this can be called directly for testing.
 */
FOUNDATION_EXPORT void Ios_demoStartDemo(void);

#endif
