// Objective-C API for talking to github.com/agiangrant/centered/examples/ios_demo Go package.
//   gobind -lang=objc github.com/agiangrant/centered/examples/ios_demo
//
// File is generated by gobind. Do not edit.

#ifndef __Ios_demo_H__
#define __Ios_demo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Ios_demoDemoWidgetRefs;

/**
 * DemoWidgetRefs holds references to widgets we want to interact with
 */
@interface Ios_demoDemoWidgetRefs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field DemoWidgetRefs.CounterText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.StatusText with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.Button1 with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.Button2 with unsupported type: *github.com/agiangrant/centered/retained.Widget

// skipped field DemoWidgetRefs.Button3 with unsupported type: *github.com/agiangrant/centered/retained.Widget

@end

/**
 * Dummy export required by gomobile
 */
FOUNDATION_EXPORT void Ios_demoDummy(void);

/**
 * Main is exported for testing on desktop
 */
FOUNDATION_EXPORT void Ios_demoMain(void);

/**
 * StartDemo initializes and starts the demo app.
This should be called from the iOS app's initialization.
 */
FOUNDATION_EXPORT void Ios_demoStartDemo(void);

#endif
