package commands

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

// Init implements the 'ctd init' command
func Init(args []string) error {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	name := fs.String("name", "", "Project name")
	identifier := fs.String("id", "", "App identifier (e.g., com.example.myapp)")
	force := fs.Bool("force", false, "Overwrite existing files")
	fs.Parse(args)

	// Get project name from args or current directory
	projectName := *name
	if projectName == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return err
		}
		projectName = filepath.Base(cwd)
	}

	// Generate identifier if not provided
	appIdentifier := *identifier
	if appIdentifier == "" {
		appIdentifier = "com.example." + sanitizeName(projectName)
	}

	// Check if ctd.toml already exists
	if _, err := os.Stat("ctd.toml"); err == nil && !*force {
		return fmt.Errorf("ctd.toml already exists (use --force to overwrite)")
	}

	fmt.Printf("Initializing CTD project: %s\n", projectName)

	// Create ctd.toml with a nice template (SaveConfig uses TOML marshal which isn't as readable)
	ctdToml := fmt.Sprintf(`# CTD Project Configuration
# Generated by 'ctd init'

[app]
name = "%s"
identifier = "%s"
version = "1.0.0"
# description = "My awesome app"
# author = "Your Name"
# website = "https://example.com"

# App permissions - enable what your app needs
[permissions]
network = true              # Internet access
# camera = true             # Camera access
# microphone = true         # Microphone access
# photo_library = true      # Photo library access
# location = true           # Location services
# bluetooth = true          # Bluetooth access
# notifications = true      # Push notifications
# file_access = true        # File system access

# Custom usage descriptions for iOS (required when permission is enabled)
# camera_usage = "This app uses the camera for..."
# microphone_usage = "This app uses the microphone for..."
# photo_library_usage = "This app accesses photos for..."
# location_usage = "This app uses your location for..."

[ios]
deployment_target = "15.0"
# development_team = "YOUR_TEAM_ID"  # From Apple Developer account
bundle_identifier = "%s"
category = "public.app-category.utilities"
device_family = "both"  # iphone, ipad, or both
# icon_path = "assets/AppIcon.png"

[android]
min_sdk = 26        # Android 8.0+
target_sdk = 34     # Android 14
package_name = "%s"
# icon_path = "assets/icon.png"
# icon_foreground = "assets/icon_foreground.png"
# icon_background = "assets/icon_background.png"

[build]
engine_dir = "engine"
output_dir = "build"
theme_file = "theme.toml"
entry_point = "."
`, projectName, appIdentifier, appIdentifier, appIdentifier)

	if err := os.WriteFile("ctd.toml", []byte(ctdToml), 0644); err != nil {
		return fmt.Errorf("failed to create ctd.toml: %w", err)
	}
	fmt.Println("  ✓ Created ctd.toml")

	// Create theme.toml if it doesn't exist
	if _, err := os.Stat("theme.toml"); os.IsNotExist(err) {
		if err := os.WriteFile("theme.toml", []byte(defaultThemeToml), 0644); err != nil {
			return fmt.Errorf("failed to create theme.toml: %w", err)
		}
		fmt.Println("  ✓ Created theme.toml")
	}

	// Create tw directory
	if err := os.MkdirAll("tw", 0755); err != nil {
		return fmt.Errorf("failed to create tw directory: %w", err)
	}

	// Create .gitignore if it doesn't exist
	if _, err := os.Stat(".gitignore"); os.IsNotExist(err) {
		if err := os.WriteFile(".gitignore", []byte(defaultGitignore), 0644); err != nil {
			return fmt.Errorf("failed to create .gitignore: %w", err)
		}
		fmt.Println("  ✓ Created .gitignore")
	}

	// Create basic main.go if it doesn't exist
	if _, err := os.Stat("main.go"); os.IsNotExist(err) {
		mainGo := fmt.Sprintf(mainGoTemplate, projectName, appIdentifier)
		if err := os.WriteFile("main.go", []byte(mainGo), 0644); err != nil {
			return fmt.Errorf("failed to create main.go: %w", err)
		}
		fmt.Println("  ✓ Created main.go")
	}

	// Check for go.mod
	if _, err := os.Stat("go.mod"); os.IsNotExist(err) {
		fmt.Println("")
		fmt.Println("No go.mod found. Create one with:")
		fmt.Printf("  go mod init %s\n", appIdentifier)
		fmt.Println("  go get github.com/agiangrant/ctd")
	}

	// Fetch engine source (optional, will be fetched on first build if skipped)
	fmt.Println("")
	if err := FetchEngineSource(false); err != nil {
		fmt.Printf("Note: Could not fetch engine source: %v\n", err)
		fmt.Println("The engine will be fetched automatically on first build.")
	}

	fmt.Println("")
	fmt.Println("✓ Project initialized!")
	fmt.Println("")
	fmt.Println("Next steps:")
	fmt.Println("  1. Build and run (engine compiles automatically on first build):")
	fmt.Println("     ctd build           # Build for current platform")
	fmt.Println("     ctd dev             # Development mode with hot reload")
	fmt.Println("")
	fmt.Println("  2. For mobile development:")
	fmt.Println("     ctd create-ios      # Create iOS project")
	fmt.Println("     ctd create-android  # Create Android project")
	fmt.Println("     ctd run-ios         # Run on iOS simulator")
	fmt.Println("     ctd run-android     # Run on Android emulator")

	return nil
}

const defaultThemeToml = `# CTD Theme Configuration
# Customize colors, spacing, fonts, and breakpoints

# Custom font families
# Use system font names or paths to bundled fonts
[fonts]
# sans = "system"
# serif = "Times New Roman"
# mono = "Menlo"
# custom = "./fonts/MyFont.ttf"

# Theme customization
[theme]

# Responsive breakpoints (in pixels)
[theme.breakpoints]
# sm = 640
# md = 768
# lg = 1024
# xl = 1280
# 2xl = 1536

# Custom spacing scale
[theme.spacing]
# 0 = "0"
# 1 = "0.25rem"
# 2 = "0.5rem"
# custom = "100px"

# Custom colors
[theme.colors]
# primary = "#3B82F6"
# secondary = "#10B981"
# accent = "#F59E0B"

# Custom utility classes
[utilities]
# btn-primary = ["bg-blue-500", "text-white", "px-4", "py-2", "rounded-lg"]
# card = ["bg-white", "rounded-xl", "shadow-lg", "p-6"]
`

const defaultGitignore = `# CTD cache (engine source + built libraries)
.ctd/

# Generated Go files
tw/generated.go

# Build output
build/
dist/

# Rust build artifacts (if engine is local)
engine/target/

# Go binaries
*.exe
*.exe~
*.dll
*.so
*.dylib

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS files
.DS_Store
Thumbs.db
`

const mainGoTemplate = `package main

import (
	"github.com/agiangrant/ctd"
)

func main() {
	ctd.Run(ctd.AppConfig{
		Title:  "%s",
		Width:  800,
		Height: 600,
	}, buildUI)
}

func buildUI() *ctd.Widget {
	return ctd.VStack(
		ctd.Text("Welcome to %s").
			Class("text-2xl font-bold text-white"),

		ctd.Spacer(),

		ctd.Text("Built with CTD").
			Class("text-gray-400"),
	).Class("flex-1 items-center justify-center bg-gray-900")
}
`
