
// Objective-C API for talking to the following Go packages
//
//	github.com/agiangrant/centered/examples/ios_demo
//
// File is generated by gomobile bind. Do not edit.
#ifndef __CenteredDemo_FRAMEWORK_H__
#define __CenteredDemo_FRAMEWORK_H__

#include "Ios_demo.objc.h"
#include "Universe.objc.h"

#endif
